[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm",
    "cython",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
